local options = {
    ensure_installed = {
        "bash",
        "c",
        "cmake",
        "cpp",
        "fish",
        "go",
        "lua",
        "luadoc",
        "markdown",
        "markdown_inline",
        "python",
        "rust",
        "toml",
        "vim",
        "vimdoc",
        "yaml",
        "typescript",
        "tsx",
        "javascript",
        "jsdoc",
        "dockerfile",
        "css",
        "html",
        "json",
        "json5",
        "java",
        "graphql",
        "properties",
        "xml",
        "nix",
        "prisma",
        "proto",
        "sql",
        "regex",
    },

    highlight = {
        enable = true,
        use_languagetree = true,
    },

    indent = { enable = true },
}

require("nvim-treesitter.configs").setup(options)
